# Generated by Django 4.2.6 on 2023-11-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0004_alter_task_author_alter_task_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(blank=True, to="labels.label"),
        ),
    ]
