# Generated by Django 4.2.6 on 2023-11-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
